Docker deploy (#30)
* e2e

* update dockerfile

* update dockerfile

* update nginx config

* test docker workflow

* test-workflow

* test unittest

* update workflow, remove test workflow

---------

Co-authored-by: thiendangncc <72342184+thiendangncc@users.noreply.github.com>
Co-authored-by: thiennguyenncc <thien.nguyenthai@ncc.asia>

diff --git a/.github/workflows/docker-deploy-dev.yml b/.github/workflows/docker-deploy-dev.yml
--- a/.github/workflows/docker-deploy-dev.yml
+++ b/.github/workflows/docker-deploy-dev.yml
@@ -1,11 +1,9 @@
-name: Testing
+name: Deploy NCC-ERP-AMS-BE to server using Docker
 
 on:
-  pull_request:
-    types:
-      - opened
-      - synchronize
-      - reopened
+  push:
+    branches:
+      - develop
 
 jobs:
   tests:
@@ -97,15 +95,54 @@ jobs:
         uses: actions/github-script@v5
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
-
           script: |
             const fs = require('fs');
-
             const coverageContent = fs.readFileSync('./tests/_output/coverage.txt', 'utf-8');
-
             await github.rest.issues.createComment({
               owner: context.repo.owner,
               repo: context.repo.repo,
               issue_number: context.issue.number,
               body: 'Code Coverage Results:\n\n```\n' + coverageContent + '\n```\n',
             });
+
+  build:
+    runs-on: self-hosted
+    needs:
+      - tests
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Remove old image
+        run: docker rmi ncc-erp-ams-be:latest || true
+
+      - name: Build Docker image
+        run: docker build -t ncc-erp-ams-be:latest -f Dockerfile.php8.0 .
+
+  deploy:
+    runs-on: self-hosted
+    needs:
+      - build
+
+    steps:
+      - name: Check Docker installation
+        run: |
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker could not be found. Please install Docker."
+            exit 1
+          else
+            echo "Docker is already installed."
+          fi
+
+      - name: Stop and remove old container
+        run: |
+          docker compose -f /home/nccsoft/ams-dev-docker/docker-compose.dev.yml down
+
+      - name: Run Docker Compose
+        run: |
+          docker compose -f /home/nccsoft/ams-dev-docker/docker-compose.dev.yml up -d
